server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    compacted_block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
    block:
      bloom_filter_false_positive: .05
    wal:
      path: /tmp/tempo/wal

metrics_generator:
  processor: {}
  storage:
    path: /tmp/tempo/metrics
    pool:
      max_workers: 100
      queue_depth: 10000